services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: beaver
    restart: always
    working_dir: /var/www/
    volumes:
      - ../:/var/www
      - ../composer.json:/composer.json:ro

  nginx:
    image: nginx:1.19-alpine
    container_name: beaver-web
    restart: always
    ports: 
      - "8090:80"
    volumes:
      - ../:/var/www/
      - ../nginx:/etc/nginx/conf.d
  
  db:
    container_name: beaver-db
    image: mysql:8.0
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_db
    ports:
      - "3307:3307"