services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: beaver
    restart: always
    working_dir: /var/www/
    volumes:
      - ../:/var/www
      - ../composer.json:/var/www/composer.json:ro

  nginx:
    image: nginx:1.19-alpine
    container_name: beaver-web
    restart: always
    ports: 
      - "8090:80"
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d
    
